# Generated by Django 5.1 on 2024-11-14 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_wrapped_country_wrapped_display_name_wrapped_email_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wrapped',
            name='user',
        ),
        migrations.AlterField(
            model_name='wrapped',
            name='spotify_user_id',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
